{{- if and .Values.websocket.enabled (index .Values.worker "websocket").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "larakube.fullname" . }}-websocket
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
  {{- with .Values.websocket.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: {{ (index .Values.worker "websocket").containerPort }}
      protocol: TCP
      name: websocket
  selector:
    {{- include "larakube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker-websocket
{{- end }}