{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel-octane.fullname" . }}-migration
  labels:
    {{- include "laravel-octane.labels" . | nindent 4 }}
    laravel.com/job-type: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "laravel-octane.selectorLabels" . | nindent 8 }}
        laravel.com/job-type: migration
      {{- with .Values.migration.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.migration.restartPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "laravel-octane.serviceAccountName" . }}
      {{- end }}
      volumes:
        - name: env
          secret:
            secretName: {{ if .Values.app.envSecretName }} {{ .Values.app.envSecretName }} {{ else }} {{ .Release.Name }}-env {{ end }}
        - name: php-ini-config
          configMap:
            name: {{ if .Values.phpIni.configName }} {{ .Values.phpIni.configName }} {{ else }} {{ .Release.Name }}-php-ini-config {{ end }}
        {{- with .Values.migration.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command: {{ toYaml .Values.migration.command | nindent 12 }}
          env:
            {{- with .Values.migration.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: env
              mountPath: /var/www/html/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/conf.d/custom.ini
              subPath: custom.ini
            {{- with .Values.migration.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
{{- end }} 